name: expandable_view
description: Expandable view that hides on a button at the bottom of the parent widget and expands when clicked to display a different widget.
version: 0.1.0
author: José Luna <josluna1098@gmail.com>
homepage: https://github.com/JosLuna98/expandable_view

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
